# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# title: 4 х 40 - Задачник по математике
# email: alexandervpetrov@gmail.com
# description: > # this means to ignore newlines until "baseurl:"
  # Write an awesome description for your new site here. You can edit this
  # line in _config.yml. It will appear in your document head meta (for
  # Google search results) and in your feed.xml site description.

baseurl: "/book.4x40" # the subpath of your site, e.g. /blog
url: "http://alexandervpetrov.github.io" # the base hostname & protocol for your site

book:
  version: "1.2.0"
  date: "28.10.2016"
  buy:
    url: "https://goo.gl/forms/pY5cnvqZKyt7HI6U2"
    details: "64 сторінки, формат А5, гнучка обкладинка"
  a5:
    url: "https://github.com/alexandervpetrov/book.4x40/files/557687/4x40-book.v1.2.0.2016-10-28.71d308b.a5.pdf"
    details: "64 сторінки, формат А5, у кольорі, обкладинка"
  ebook:
    url: "https://github.com/alexandervpetrov/book.4x40/files/557689/4x40-book.v1.2.0.2016-10-28.71d308b.ebook.pdf"
    details: "60 сторінок, формат 120 x 160 мм, малі поля, у кольорі, без обкладинки"
  online:
    url: "https://github.com/alexandervpetrov/book.4x40/files/557688/4x40-book.v1.2.0.2016-10-28.71d308b.online.pdf"
    details: "49 сторінок, формат Letter, у кольорі, без обкладинки"

# twitter_username: jekyllrb
# github_username:  alexandervpetrov

# Build settings
markdown: kramdown
# theme: minima
